#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadNeuseCSV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nssnc")]
	public partial class productImagesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertproductimage(productimage instance);
    partial void Updateproductimage(productimage instance);
    partial void Deleteproductimage(productimage instance);
    #endregion
		
		public productImagesDataContext() : 
				base(global::LoadNeuseCSV.Properties.Settings.Default.nssncConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public productImagesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public productImagesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public productImagesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public productImagesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<productimage> productimages
		{
			get
			{
				return this.GetTable<productimage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productimages")]
	public partial class productimage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _imageProduct;
		
		private string _imageSrc;
		
		private int _imageNumber;
		
		private short _imageType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnimageProductChanging(string value);
    partial void OnimageProductChanged();
    partial void OnimageSrcChanging(string value);
    partial void OnimageSrcChanged();
    partial void OnimageNumberChanging(int value);
    partial void OnimageNumberChanged();
    partial void OnimageTypeChanging(short value);
    partial void OnimageTypeChanged();
    #endregion
		
		public productimage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageProduct", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string imageProduct
		{
			get
			{
				return this._imageProduct;
			}
			set
			{
				if ((this._imageProduct != value))
				{
					this.OnimageProductChanging(value);
					this.SendPropertyChanging();
					this._imageProduct = value;
					this.SendPropertyChanged("imageProduct");
					this.OnimageProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageSrc", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string imageSrc
		{
			get
			{
				return this._imageSrc;
			}
			set
			{
				if ((this._imageSrc != value))
				{
					this.OnimageSrcChanging(value);
					this.SendPropertyChanging();
					this._imageSrc = value;
					this.SendPropertyChanged("imageSrc");
					this.OnimageSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int imageNumber
		{
			get
			{
				return this._imageNumber;
			}
			set
			{
				if ((this._imageNumber != value))
				{
					this.OnimageNumberChanging(value);
					this.SendPropertyChanging();
					this._imageNumber = value;
					this.SendPropertyChanged("imageNumber");
					this.OnimageNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageType", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short imageType
		{
			get
			{
				return this._imageType;
			}
			set
			{
				if ((this._imageType != value))
				{
					this.OnimageTypeChanging(value);
					this.SendPropertyChanging();
					this._imageType = value;
					this.SendPropertyChanged("imageType");
					this.OnimageTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
