#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadNeuseCSV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nssnc")]
	public partial class searchCriteriaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsearchcriteria(searchcriteria instance);
    partial void Updatesearchcriteria(searchcriteria instance);
    partial void Deletesearchcriteria(searchcriteria instance);
    #endregion
		
		public searchCriteriaDataContext() : 
				base(global::LoadNeuseCSV.Properties.Settings.Default.nssncConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public searchCriteriaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public searchCriteriaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public searchCriteriaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public searchCriteriaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<searchcriteria> searchcriterias
		{
			get
			{
				return this.GetTable<searchcriteria>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.searchcriteria")]
	public partial class searchcriteria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _scID;
		
		private System.Nullable<int> _scOrder;
		
		private System.Nullable<int> _scGroup;
		
		private string _scWorkingName;
		
		private string _scName;
		
		private string _scName2;
		
		private string _scName3;
		
		private string _scLogo;
		
		private string _scURL;
		
		private string _scURL2;
		
		private string _scURL3;
		
		private string _scEmail;
		
		private string _scDescription;
		
		private string _scDescription2;
		
		private string _scDescription3;
		
		private string _scNotes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnscIDChanging(int value);
    partial void OnscIDChanged();
    partial void OnscOrderChanging(System.Nullable<int> value);
    partial void OnscOrderChanged();
    partial void OnscGroupChanging(System.Nullable<int> value);
    partial void OnscGroupChanged();
    partial void OnscWorkingNameChanging(string value);
    partial void OnscWorkingNameChanged();
    partial void OnscNameChanging(string value);
    partial void OnscNameChanged();
    partial void OnscName2Changing(string value);
    partial void OnscName2Changed();
    partial void OnscName3Changing(string value);
    partial void OnscName3Changed();
    partial void OnscLogoChanging(string value);
    partial void OnscLogoChanged();
    partial void OnscURLChanging(string value);
    partial void OnscURLChanged();
    partial void OnscURL2Changing(string value);
    partial void OnscURL2Changed();
    partial void OnscURL3Changing(string value);
    partial void OnscURL3Changed();
    partial void OnscEmailChanging(string value);
    partial void OnscEmailChanged();
    partial void OnscDescriptionChanging(string value);
    partial void OnscDescriptionChanged();
    partial void OnscDescription2Changing(string value);
    partial void OnscDescription2Changed();
    partial void OnscDescription3Changing(string value);
    partial void OnscDescription3Changed();
    partial void OnscNotesChanging(string value);
    partial void OnscNotesChanged();
    #endregion
		
		public searchcriteria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int scID
		{
			get
			{
				return this._scID;
			}
			set
			{
				if ((this._scID != value))
				{
					this.OnscIDChanging(value);
					this.SendPropertyChanging();
					this._scID = value;
					this.SendPropertyChanged("scID");
					this.OnscIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scOrder", DbType="Int")]
		public System.Nullable<int> scOrder
		{
			get
			{
				return this._scOrder;
			}
			set
			{
				if ((this._scOrder != value))
				{
					this.OnscOrderChanging(value);
					this.SendPropertyChanging();
					this._scOrder = value;
					this.SendPropertyChanged("scOrder");
					this.OnscOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scGroup", DbType="Int")]
		public System.Nullable<int> scGroup
		{
			get
			{
				return this._scGroup;
			}
			set
			{
				if ((this._scGroup != value))
				{
					this.OnscGroupChanging(value);
					this.SendPropertyChanging();
					this._scGroup = value;
					this.SendPropertyChanged("scGroup");
					this.OnscGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scWorkingName", DbType="NVarChar(255)")]
		public string scWorkingName
		{
			get
			{
				return this._scWorkingName;
			}
			set
			{
				if ((this._scWorkingName != value))
				{
					this.OnscWorkingNameChanging(value);
					this.SendPropertyChanging();
					this._scWorkingName = value;
					this.SendPropertyChanged("scWorkingName");
					this.OnscWorkingNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scName", DbType="NVarChar(255)")]
		public string scName
		{
			get
			{
				return this._scName;
			}
			set
			{
				if ((this._scName != value))
				{
					this.OnscNameChanging(value);
					this.SendPropertyChanging();
					this._scName = value;
					this.SendPropertyChanged("scName");
					this.OnscNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scName2", DbType="NVarChar(255)")]
		public string scName2
		{
			get
			{
				return this._scName2;
			}
			set
			{
				if ((this._scName2 != value))
				{
					this.OnscName2Changing(value);
					this.SendPropertyChanging();
					this._scName2 = value;
					this.SendPropertyChanged("scName2");
					this.OnscName2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scName3", DbType="NVarChar(255)")]
		public string scName3
		{
			get
			{
				return this._scName3;
			}
			set
			{
				if ((this._scName3 != value))
				{
					this.OnscName3Changing(value);
					this.SendPropertyChanging();
					this._scName3 = value;
					this.SendPropertyChanged("scName3");
					this.OnscName3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scLogo", DbType="NVarChar(255)")]
		public string scLogo
		{
			get
			{
				return this._scLogo;
			}
			set
			{
				if ((this._scLogo != value))
				{
					this.OnscLogoChanging(value);
					this.SendPropertyChanging();
					this._scLogo = value;
					this.SendPropertyChanged("scLogo");
					this.OnscLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scURL", DbType="NVarChar(255)")]
		public string scURL
		{
			get
			{
				return this._scURL;
			}
			set
			{
				if ((this._scURL != value))
				{
					this.OnscURLChanging(value);
					this.SendPropertyChanging();
					this._scURL = value;
					this.SendPropertyChanged("scURL");
					this.OnscURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scURL2", DbType="NVarChar(255)")]
		public string scURL2
		{
			get
			{
				return this._scURL2;
			}
			set
			{
				if ((this._scURL2 != value))
				{
					this.OnscURL2Changing(value);
					this.SendPropertyChanging();
					this._scURL2 = value;
					this.SendPropertyChanged("scURL2");
					this.OnscURL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scURL3", DbType="NVarChar(255)")]
		public string scURL3
		{
			get
			{
				return this._scURL3;
			}
			set
			{
				if ((this._scURL3 != value))
				{
					this.OnscURL3Changing(value);
					this.SendPropertyChanging();
					this._scURL3 = value;
					this.SendPropertyChanged("scURL3");
					this.OnscURL3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scEmail", DbType="NVarChar(255)")]
		public string scEmail
		{
			get
			{
				return this._scEmail;
			}
			set
			{
				if ((this._scEmail != value))
				{
					this.OnscEmailChanging(value);
					this.SendPropertyChanging();
					this._scEmail = value;
					this.SendPropertyChanged("scEmail");
					this.OnscEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scDescription", DbType="NVarChar(MAX)")]
		public string scDescription
		{
			get
			{
				return this._scDescription;
			}
			set
			{
				if ((this._scDescription != value))
				{
					this.OnscDescriptionChanging(value);
					this.SendPropertyChanging();
					this._scDescription = value;
					this.SendPropertyChanged("scDescription");
					this.OnscDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scDescription2", DbType="NVarChar(MAX)")]
		public string scDescription2
		{
			get
			{
				return this._scDescription2;
			}
			set
			{
				if ((this._scDescription2 != value))
				{
					this.OnscDescription2Changing(value);
					this.SendPropertyChanging();
					this._scDescription2 = value;
					this.SendPropertyChanged("scDescription2");
					this.OnscDescription2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scDescription3", DbType="NVarChar(MAX)")]
		public string scDescription3
		{
			get
			{
				return this._scDescription3;
			}
			set
			{
				if ((this._scDescription3 != value))
				{
					this.OnscDescription3Changing(value);
					this.SendPropertyChanging();
					this._scDescription3 = value;
					this.SendPropertyChanged("scDescription3");
					this.OnscDescription3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scNotes", DbType="NVarChar(MAX)")]
		public string scNotes
		{
			get
			{
				return this._scNotes;
			}
			set
			{
				if ((this._scNotes != value))
				{
					this.OnscNotesChanging(value);
					this.SendPropertyChanging();
					this._scNotes = value;
					this.SendPropertyChanged("scNotes");
					this.OnscNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
